/// Flutter icons Budget_tracker_icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Budget_tracker_icons
///      fonts:
///       - asset: fonts/Budget_tracker_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BudgetIcons {
  BudgetIcons._();

  static const _kFontFam = 'BudgetIcons';
  static const String? _kFontPkg = null;

  static const IconData others = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainment = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apparel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportation = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
