// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACB6nWFNDqXJ7bjbmYCqPLRlAquTXU89c',
    appId: '1:295527037220:web:3ae2b3b571acd8a1055bb1',
    messagingSenderId: '295527037220',
    projectId: 'sidekickapp-10912',
    authDomain: 'sidekickapp-10912.firebaseapp.com',
    storageBucket: 'sidekickapp-10912.appspot.com',
    measurementId: 'G-MKLE77JT6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JvYi1G3bSVp7U8C5QpmflghQmne3Sj0',
    appId: '1:295527037220:android:061d2d388178d313055bb1',
    messagingSenderId: '295527037220',
    projectId: 'sidekickapp-10912',
    storageBucket: 'sidekickapp-10912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GtBX8VQCopnno_n_lzyWClrnLrs5Kx4',
    appId: '1:295527037220:ios:87401e0b303a89c1055bb1',
    messagingSenderId: '295527037220',
    projectId: 'sidekickapp-10912',
    storageBucket: 'sidekickapp-10912.appspot.com',
    iosBundleId: 'com.example.sidekickApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4GtBX8VQCopnno_n_lzyWClrnLrs5Kx4',
    appId: '1:295527037220:ios:d24433839604400a055bb1',
    messagingSenderId: '295527037220',
    projectId: 'sidekickapp-10912',
    storageBucket: 'sidekickapp-10912.appspot.com',
    iosBundleId: 'com.example.sidekickApp.RunnerTests',
  );
}
